(set-info :original "docker_example.bc")
(set-info :authors "SeaHorn v.0.1.0-rc3")
(declare-rel verifier.error (Bool Bool Bool ))
(declare-rel main@_sm4 (Bool (Array Int Int) ))
(declare-rel main@_call13 (Bool ))
(declare-rel main@_18 (Bool Int ))
(declare-rel main@.split (Bool ))
(declare-var main@%_19_0 Int )
(declare-var main@%_20_0 Int )
(declare-var main@%sm4_0 (Array Int Int) )
(declare-var main@%sm5_0 (Array Int Int) )
(declare-var main@%sm6_0 (Array Int Int) )
(declare-var main@%sm7_0 (Array Int Int) )
(declare-var main@%sm_0 (Array Int Int) )
(declare-var main@%_call_0 Int )
(declare-var main@%_call8_0 Int )
(declare-var main@%_sm1_0 Int )
(declare-var main@%sm1_0 (Array Int Int) )
(declare-var main@%sm2_0 (Array Int Int) )
(declare-var main@%sm3_0 (Array Int Int) )
(declare-var main@%_5_0 Int )
(declare-var main@%_6_0 Bool )
(declare-var main@%_call9_0 Int )
(declare-var main@%_8_0 Int )
(declare-var main@%_9_0 Bool )
(declare-var main@%_call10_0 Int )
(declare-var main@%_11_0 Int )
(declare-var main@%_call11_0 Int )
(declare-var main@%_call12_0 Int )
(declare-var main@%_14_0 Int )
(declare-var main@%_15_0 Int )
(declare-var main@%_br_0 Bool )
(declare-var error.flag_0 Bool )
(declare-var @.str_0 Int )
(declare-var error.flag_1 Bool )
(rule (verifier.error false false false))
(rule (verifier.error false true true))
(rule (verifier.error true false true))
(rule (verifier.error true true true))
(rule (=> (not error.flag_0) (main@_sm4 error.flag_0 main@%sm7_0)))
(rule (=> (and (main@_sm4 error.flag_0 main@%sm7_0)
         (not error.flag_0)
         (= main@%sm_0 main@%sm7_0)
         (> main@%_call_0 0)
         (> main@%_call8_0 0)
         (> main@%_sm1_0 0)
         (= main@%sm1_0 (store main@%sm6_0 main@%_call_0 0))
         (= main@%sm2_0 (store main@%sm4_0 main@%_call8_0 90))
         (= main@%sm3_0 (store main@%sm5_0 main@%_sm1_0 100))
         (= main@%_5_0 (select main@%sm2_0 main@%_call8_0))
         (= main@%_6_0 (> main@%_5_0 0))
         (= main@%_call9_0 (ite main@%_6_0 1 0))
         (or error.flag_0 main@%_6_0)
         (= main@%_8_0 (select main@%sm3_0 main@%_sm1_0))
         (= main@%_9_0 (> main@%_8_0 0))
         (= main@%_call10_0 (ite main@%_9_0 1 0))
         (or error.flag_0 main@%_9_0)
         (= main@%_11_0 (select main@%sm2_0 main@%_call8_0))
         (= main@%_call11_0 (+ main@%_11_0 100))
         (= main@%_call12_0 (select main@%sm2_0 main@%_call8_0))
         (= main@%_14_0 (select main@%sm3_0 main@%_sm1_0))
         (= main@%_15_0 (+ main@%_call12_0 main@%_14_0))
         (= main@%_br_0 (> main@%_call11_0 main@%_15_0))
         (or error.flag_0 main@%_br_0))
    (main@_18 error.flag_0 @.str_0)))
(rule (=> (and (main@_sm4 error.flag_0 main@%sm7_0)
         (not error.flag_0)
         (= main@%sm_0 main@%sm7_0)
         (> main@%_call_0 0)
         (> main@%_call8_0 0)
         (> main@%_sm1_0 0)
         (= main@%sm1_0 (store main@%sm6_0 main@%_call_0 0))
         (= main@%sm2_0 (store main@%sm4_0 main@%_call8_0 90))
         (= main@%sm3_0 (store main@%sm5_0 main@%_sm1_0 100))
         (= main@%_5_0 (select main@%sm2_0 main@%_call8_0))
         (= main@%_6_0 (> main@%_5_0 0))
         (= main@%_call9_0 (ite main@%_6_0 1 0))
         (or error.flag_0 main@%_6_0)
         (= main@%_8_0 (select main@%sm3_0 main@%_sm1_0))
         (= main@%_9_0 (> main@%_8_0 0))
         (= main@%_call10_0 (ite main@%_9_0 1 0))
         (or error.flag_0 main@%_9_0)
         (= main@%_11_0 (select main@%sm2_0 main@%_call8_0))
         (= main@%_call11_0 (+ main@%_11_0 100))
         (= main@%_call12_0 (select main@%sm2_0 main@%_call8_0))
         (= main@%_14_0 (select main@%sm3_0 main@%_sm1_0))
         (= main@%_15_0 (+ main@%_call12_0 main@%_14_0))
         (= main@%_br_0 (> main@%_call11_0 main@%_15_0))
         (or error.flag_0 (not main@%_br_0))
         (verifier.error true error.flag_0 error.flag_1))
    (main@_call13 error.flag_1)))
(rule (let ((a!1 (and (main@_18 error.flag_0 @.str_0)
                (not error.flag_0)
                (= main@%_19_0 1)
                (= main@%_20_0 (+ @.str_0 (* 0 15) (* 0 1)))
                (or (<= @.str_0 0) (> main@%_20_0 0)))))
  (=> a!1 (main@.split error.flag_0))))
(rule (=> (and (main@_sm4 error.flag_0 main@%sm7_0) error.flag_0)
    (main@.split error.flag_0)))
(rule (=> (and (main@_call13 error.flag_0) error.flag_0) (main@.split error.flag_0)))
(rule (=> (and (main@_18 error.flag_0 @.str_0) error.flag_0)
    (main@.split error.flag_0)))
(query (main@.split true))

