##### Defines two organizations   ####
##### Orderer for airline network ####
OrdererOrgs:
  - Name: Orderer
    Domain: acme.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: orderer
      
PeerOrgs:
  #### Peers for acme airline
  - Name: acme
    Domain: acme.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: devpeer
        CommonName: devpeer
    Users:
      Count: 1
  #### Peers for budget airline
  - Name: budget
    Domain: budget.com
    EnableNodeOUs: true
    Specs:
      - Hostname: devpeer
        CommonName: devpeer
    Users:
      Count: 1


      