# Release 1.1 
# DO NOT USE This as many aspects deprecated in Release 1.2
# Kept here for reference only

Organizations:
  - &Orderer
    Name: Orderer
    ID: OrdererMSP
    MSPDir: ./crypto-config/ordererOrganizations/acme.com/msp

  - &Org1
    Name: Org1
    ID: Org1MSP
    MSPDir: ./crypto-config/peerOrganizations/acme.com/msp
    AnchorPeers:
      - Host: localhost
        Port: 7051

# Configuration for the Orderer
Orderer: &OrdererDefaults

  OrdererType: solo

  Addresses:
    - localhost:7050

  # Batch Timeout: The amount of time to wait before creating a batch
  BatchTimeout: 2s

  # Batch Size: Controls the number of messages batched into a block
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 98 MB
    PreferredMaxBytes: 512 KB

Application: &ApplicationDefaults
      Organizations:

Channel: &ChannelDefaults

Profiles:

  AcmeOrdererGenesis:
      Orderer:
          <<: *OrdererDefaults
          Organizations:
              - *Orderer
      Consortiums:
          AirlineConsortium:
              Organizations:
                  - *Org1
  AcmeChannel:
    Consortium: AirlineConsortium
    Application:
        <<: *ApplicationDefaults
        Organizations:
            - *Org1