# Removes components generated by orderer

rm -rf ledger 2> /dev/null
rm -rf /home/vagrant/ledgers/orderer/multi-org/ledger 2> /dev/null
rm ./trace/*  2> /dev/null
rm ./temp/* 2> /dev/null


if [ -z $1 ];
then
    echo 'Deleted the ledger data only.'
    echo 'To delete all artifacts use:  ./clean.sh  all'
    exit 0;
fi

if [ $1 = 'all' ] 
then
    rm *.block 2> /dev/null
    rm *.tx 2> /dev/null
    rm -rf crypto-config 2> /dev/null
    rm -rf ./temp

    echo 'Deleted all artifacts.'
else
    echo 'Deleted the ledger data only.'
    echo 'To delete all artifacts use:  ./clean.sh  all'
fi
