version: '2'

networks:
  crosspaymentchannel:

# Storage outside the containers
volumes:
  data-orderer.rbi.com:
  data-peer1.rbi.com:
  data-peer1.icici.com:
  data-peer1.hsbc.com:
  data-peer1.boa.com:
  data-peer1.hdfc.com:
  data-peer1.nycb.com:

services:

  # Orderer service
  orderer.rbi.com:
    container_name: orderer.rbi.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    command: orderer
    # Override environment variables for orderer in this section
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=ERROR
    # Host folder mappings
    volumes:
    # Folder with genesis block
    - ${PWD}/../orderer/multi-org-banks:/var/hyperledger/config
    # Map the folder with MSP for orderer
    - ${PWD}/../orderer/multi-org-banks/crypto-config/ordererOrganizations/rbi.com/orderers/orderer.rbi.com/msp:/var/hyperledger/msp
    # Added to support the TLS setup
    - ${PWD}/../orderer/multi-org-banks/crypto-config/ordererOrganizations/rbi.com/orderers/orderer.rbi.com/tls:/var/hyperledger/tls
    - data-orderer.rbi.com:/var/ledger
    ports:
      - 7050:7050
    networks:
      - crosspaymentchannel

  # rbi peer1
  peer1.rbi.com:
    container_name: peer1.rbi.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    # Override variables in this section
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=WARNING
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_crosspayment
    # Start the peer node
    command: peer node start
    # Host folder mappings
    volumes:
      # Folder with channel create tx file
      - ${PWD}/rbi-peer:/var/hyperledger/config
      # Map the folder with MSP for Peer
      - ${PWD}/../orderer/multi-org-banks/crypto-config/peerOrganizations/rbi.com/peers/rbi-main-peer/msp:/var/hyperledger/msp
      # Added to support the TLS setup
      - ${PWD}/../orderer/multi-org-banks/crypto-config/peerOrganizations/rbi.com/peers/rbi-main-peer/tls:/var/hyperledger/tls
      - /var/run/:/var/run/
      - data-peer1.rbi.com:/var/hyperledger/production
    depends_on: 
      - orderer.rbi.com
    # Map the ports on Host VM to container ports
    ports:
      - 7051:7051
      - 8051:8051
      - 9448:9448
    networks:
      - crosspaymentchannel

  # icici peer1
  peer1.icici.com:
    container_name: peer1.icici.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    # Override variables in this section
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=WARNING
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_crosspayment
    # Start the peer node
    command: peer node start
    # Host folder mappings
    volumes:
      # Folder with channel create tx file
      - ${PWD}/icici-peer:/var/hyperledger/config
      # Map the folder with MSP for Peer
      - ${PWD}/../orderer/multi-org-banks/crypto-config/peerOrganizations/icici.com/peers/icici-main-peer/msp:/var/hyperledger/msp
      # Added to support the TLS setup
      - ${PWD}/../orderer/multi-org-banks/crypto-config/peerOrganizations/icici.com/peers/icici-main-peer/tls:/var/hyperledger/tls
      - /var/run/:/var/run/
      - data-peer1.icici.com:/var/hyperledger/production
    depends_on: 
      - orderer.rbi.com
    # Map the ports on Host VM to container ports
    ports:
      - 7052:7052
      - 8052:8052
      - 9446:9446
    networks:
      - crosspaymentchannel

  # hsbc peer1
  peer1.hsbc.com:
    container_name: peer1.hsbc.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    # Override variables in this section
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=WARNING
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_crosspayment
    # Start the peer node
    command: peer node start
    # Host folder mappings
    volumes:
      # Folder with channel create tx file
      - ${PWD}/hsbc-peer:/var/hyperledger/config
      # Map the folder with MSP for Peer
      - ${PWD}/../orderer/multi-org-banks/crypto-config/peerOrganizations/hsbc.com/peers/hsbc-main-peer/msp:/var/hyperledger/msp
      # Added to support the TLS setup
      - ${PWD}/../orderer/multi-org-banks/crypto-config/peerOrganizations/hsbc.com/peers/hsbc-main-peer/tls:/var/hyperledger/tls
      - /var/run/:/var/run/
      - data-peer1.hsbc.com:/var/hyperledger/production
    depends_on: 
      - orderer.rbi.com
    # Map the ports on Host VM to container ports
    ports:
      - 7053:7053
      - 8053:8053
      - 9445:9445
    networks:
      - crosspaymentchannel

  # hdfc peer1
  peer1.hdfc.com:
    container_name: peer1.hdfc.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    # Override variables in this section
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=WARNING
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_crosspayment
    # Start the peer node
    command: peer node start
    # Host folder mappings
    volumes:
      # Folder with channel create tx file
      - ${PWD}/hdfc-peer:/var/hyperledger/config
      # Map the folder with MSP for Peer
      - ${PWD}/../orderer/multi-org-banks/crypto-config/peerOrganizations/hdfc.com/peers/hdfc-main-peer/msp:/var/hyperledger/msp
      # Added to support the TLS setup
      - ${PWD}/../orderer/multi-org-banks/crypto-config/peerOrganizations/hdfc.com/peers/hdfc-main-peer/tls:/var/hyperledger/tls
      - /var/run/:/var/run/
      - data-peer1.hdfc.com:/var/hyperledger/production
    depends_on: 
      - orderer.rbi.com
    # Map the ports on Host VM to container ports
    ports:
      - 7055:7055
      - 8055:8055
      - 9443:9443
    networks:
      - crosspaymentchannel

  # boa peer1
  peer1.boa.com:
    container_name: peer1.boa.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    # Override variables in this section
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=WARNING
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_crosspayment
    # Start the peer node
    command: peer node start 
    # Host folder mappings
    volumes:
      # Folder with channel create tx file
      - ${PWD}/boa-peer:/var/hyperledger/config
      # Map the folder with MSP for Peer
      - ${PWD}/../orderer/multi-org-banks/crypto-config/peerOrganizations/boa.com/peers/boa-main-peer/msp:/var/hyperledger/msp
      # Added to support the TLS setup
      - ${PWD}/../orderer/multi-org-banks/crypto-config/peerOrganizations/boa.com/peers/boa-main-peer/tls:/var/hyperledger/tls
      - /var/run/:/var/run/
      - data-peer1.boa.com:/var/hyperledger/production
    depends_on: 
      - orderer.rbi.com
    # Map the ports on Host VM to container ports
    ports:
      - 7054:7054
      - 8054:8054
      - 9444:9444
    networks:
      - crosspaymentchannel

  # nycb peer1
  peer1.nycb.com:
    container_name: peer1.nycb.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    # Override variables in this section
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=WARNING
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_crosspayment
    # Start the peer node
    command: peer node start
    # Host folder mappings
    volumes:
      # Folder with channel create tx file
      - ${PWD}/nycb-peer:/var/hyperledger/config
      # Map the folder with MSP for Peer
      - ${PWD}/../orderer/multi-org-banks/crypto-config/peerOrganizations/nycb.com/peers/nycb-main-peer/msp:/var/hyperledger/msp
      # Added to support the TLS setup
      - ${PWD}/../orderer/multi-org-banks/crypto-config/peerOrganizations/nycb.com/peers/nycb-main-peer/tls:/var/hyperledger/tls
      - /var/run/:/var/run/
      - data-peer1.nycb.com:/var/hyperledger/production
    depends_on: 
      - orderer.rbi.com
    # Map the ports on Host VM to container ports
    ports:
      - 7056:7056
      - 8056:8056
      - 9447:9447
    networks:
      - crosspaymentchannel

  # Tools container used for managing peers
  tools:
    container_name: tools
    command: /bin/bash

    # Tools container image
    image: hyperledger/fabric-tools:$IMAGE_TAG

    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=DEBUG
    # This is the working directory on login
    working_dir: /opt/scripts
    volumes:
      # Mapping for the sample chaincode folders
      - ${PWD}/../artefacts/nodechaincode:/opt/nodechaincode
      - ${PWD}/../gopath:/opt/gopath
      # Folder with channel create tx file
      - ${PWD}/config:/var/hyperledger/config
      # Map the folder to root of all Fabric CA Client crypto
      - ${PWD}/config/crypto-config/peerOrganizations:/var/hyperledger/crypto
      # VM docker stream folder mapping
      - /var/run/:/host/var/run/
      # Map the bins folder
      - ${PWD}/tool-bins:/opt/scripts
    networks:
      - crosspaymentchannel
  
  