# Extends the crypto material for the setup
# Adds a new peer for Org1

#### Peers for acme
PeerOrgs:
  # Peer configuration for ACME
  - Name: Org1
    Domain: acme.com
    Specs:
      - Hostname: devpeer2
        CommonName: devpeer2
        



      