# Defines four organizations
#  - Orderer organization
#  - Acme
#  - Budget
#  - Expo
##### Orderer for acme
OrdererOrgs:
  - Name: Orderer
    Domain: acme.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
      
#### Peers for acme
PeerOrgs:
  # Peer configuration for ACME
  - Name: Acme
    Domain: acme.com
    EnableNodeOUs: true
    Specs:
      - Hostname: peer1.acme.com
        CommonName: peer1.acme.com
    Users:
      Count: 1

  # Peer configuration for Budget
  - Name: Budget
    Domain: budget.com
    EnableNodeOUs: true
    Specs:
      - Hostname: peer1.budget.com
        CommonName: peer1.budget.com
    Users:
      Count: 1

  # Peer configuration for Budget
  - Name: Expo
    Domain: expo.com
    EnableNodeOUs: true
    Specs:
      - Hostname: peer1.expo.com
        CommonName: peer1.expo.com
    Users:
      Count: 1


      