(set-info :original "test-2.ll")
(set-info :authors "SeaHorn v.10.0.0-rc0")
(declare-rel verifier.error (Bool Bool Bool ))
(declare-rel main@_sm3 (Bool ))
(declare-rel main@_call11 (Bool ))
(declare-rel main@_18 (Bool ))
(declare-rel main@.split (Bool ))
(declare-var main@%_br12_0 Int )
(declare-var main@%sm3_0 (Array Int Int) )
(declare-var main@%sm4_0 (Array Int Int) )
(declare-var main@%sm5_0 (Array Int Int) )
(declare-var main@%_call_0 Int )
(declare-var main@%_call6_0 Int )
(declare-var main@%_sm_0 Int )
(declare-var main@%sm_0 (Array Int Int) )
(declare-var main@%sm1_0 (Array Int Int) )
(declare-var main@%sm2_0 (Array Int Int) )
(declare-var main@%_5_0 Int )
(declare-var main@%_6_0 Bool )
(declare-var main@%_call7_0 Int )
(declare-var main@%_8_0 Int )
(declare-var main@%_9_0 Bool )
(declare-var main@%_call8_0 Int )
(declare-var main@%_11_0 Int )
(declare-var main@%_call9_0 Int )
(declare-var main@%_call10_0 Int )
(declare-var main@%_14_0 Int )
(declare-var main@%_15_0 Int )
(declare-var main@%_br_0 Bool )
(declare-var error.flag_0 Bool )
(declare-var error.flag_1 Bool )
(rule (verifier.error false false false))
(rule (verifier.error false true true))
(rule (verifier.error true false true))
(rule (verifier.error true true true))
(rule (=> (not error.flag_0) (main@_sm3 error.flag_0)))
(rule (=> (and (main@_sm3 error.flag_0)
         (not error.flag_0)
         (> main@%_call_0 0)
         (> main@%_call6_0 0)
         (> main@%_sm_0 0)
         (= main@%sm_0 (store main@%sm3_0 main@%_call_0 0))
         (= main@%sm1_0 (store main@%sm4_0 main@%_call6_0 90))
         (= main@%sm2_0 (store main@%sm5_0 main@%_sm_0 100))
         (= main@%_5_0 (select main@%sm1_0 main@%_call6_0))
         (= main@%_6_0 (> main@%_5_0 0))
         (= main@%_call7_0 (ite main@%_6_0 1 0))
         (or error.flag_0 main@%_6_0)
         (= main@%_8_0 (select main@%sm2_0 main@%_sm_0))
         (= main@%_9_0 (> main@%_8_0 0))
         (= main@%_call8_0 (ite main@%_9_0 1 0))
         (or error.flag_0 main@%_9_0)
         (= main@%_11_0 (select main@%sm1_0 main@%_call6_0))
         (= main@%_call9_0 (+ main@%_11_0 50))
         (= main@%_call10_0 (select main@%sm1_0 main@%_call6_0))
         (= main@%_14_0 (select main@%sm2_0 main@%_sm_0))
         (= main@%_15_0 (+ main@%_call10_0 main@%_14_0))
         (= main@%_br_0 (> main@%_call9_0 main@%_15_0))
         (or error.flag_0 main@%_br_0))
    (main@_18 error.flag_0)))
(rule (=> (and (main@_sm3 error.flag_0)
         (not error.flag_0)
         (> main@%_call_0 0)
         (> main@%_call6_0 0)
         (> main@%_sm_0 0)
         (= main@%sm_0 (store main@%sm3_0 main@%_call_0 0))
         (= main@%sm1_0 (store main@%sm4_0 main@%_call6_0 90))
         (= main@%sm2_0 (store main@%sm5_0 main@%_sm_0 100))
         (= main@%_5_0 (select main@%sm1_0 main@%_call6_0))
         (= main@%_6_0 (> main@%_5_0 0))
         (= main@%_call7_0 (ite main@%_6_0 1 0))
         (or error.flag_0 main@%_6_0)
         (= main@%_8_0 (select main@%sm2_0 main@%_sm_0))
         (= main@%_9_0 (> main@%_8_0 0))
         (= main@%_call8_0 (ite main@%_9_0 1 0))
         (or error.flag_0 main@%_9_0)
         (= main@%_11_0 (select main@%sm1_0 main@%_call6_0))
         (= main@%_call9_0 (+ main@%_11_0 50))
         (= main@%_call10_0 (select main@%sm1_0 main@%_call6_0))
         (= main@%_14_0 (select main@%sm2_0 main@%_sm_0))
         (= main@%_15_0 (+ main@%_call10_0 main@%_14_0))
         (= main@%_br_0 (> main@%_call9_0 main@%_15_0))
         (or error.flag_0 (not main@%_br_0))
         (verifier.error true error.flag_0 error.flag_1))
    (main@_call11 error.flag_1)))
(rule (=> (and (main@_18 error.flag_0) (not error.flag_0) (= main@%_br12_0 1))
    (main@.split error.flag_0)))
(rule (=> (and (main@_sm3 error.flag_0) error.flag_0) (main@.split error.flag_0)))
(rule (=> (and (main@_call11 error.flag_0) error.flag_0) (main@.split error.flag_0)))
(rule (=> (and (main@_18 error.flag_0) error.flag_0) (main@.split error.flag_0)))
(query (main@.split true))

