Organizations:
  - &Orderer
    Name: Orderer
    ID: OrdererMSP
    MSPDir: ./crypto-config/ordererOrganizations/rbi.com/msp

  - &Org1
    Name: Org1
    ID: Org1MSP
    MSPDir: ./crypto-config/peerOrganizations/rbi.com/msp
    # AnchorPeers:
    #   - Host: localhost
    #     Port: 7051
  
  - &Org2
    Name: Org2
    ID: Org2MSP
    MSPDir: ./crypto-config/peerOrganizations/icici.com/msp
    # AnchorPeers:
    #   - Host: localhost
    #     Port: 7052

  - &Org3
    Name: Org3
    ID: Org3MSP
    MSPDir: ./crypto-config/peerOrganizations/hsbc.com/msp
    # AnchorPeers:
    #   - Host: localhost
    #     Port: 7053

  - &Org4
    Name: Org4
    ID: Org4MSP
    MSPDir: ./crypto-config/peerOrganizations/boa.com/msp
    # AnchorPeers:
    #   - Host: localhost
    #     Port: 7054

  - &Org5
    Name: Org5
    ID: Org5MSP
    MSPDir: ./crypto-config/peerOrganizations/hdfc.com/msp
    # AnchorPeers:
    #   - Host: localhost
    #     Port: 7055

  - &Org6
    Name: Org6
    ID: Org6MSP
    MSPDir: ./crypto-config/peerOrganizations/nycb.com/msp
    # AnchorPeers:
    #   - Host: localhost
    #     Port: 7056

# Configuration for the Orderer
Orderer: &OrdererDefaults

  OrdererType: solo

  Addresses:
    - orderer.rbi.com:7050

  # Batch Timeout: The amount of time to wait before creating a batch
  BatchTimeout: 4s

  # Batch Size: Controls the number of messages batched into a block
  BatchSize:
    MaxMessageCount: 20
    AbsoluteMaxBytes: 75 MB
    PreferredMaxBytes: 1024 KB
    
  Kafka:
      Brokers:
          - 127.0.0.1:9092

Application: &ApplicationDefaults
      Organizations:

Channel: &ChannelDefaults

Profiles:

  RbiOrdererGenesis:
      Orderer:
          <<: *OrdererDefaults
          Organizations:
              - *Orderer
      Consortiums:
          CrossPaymentConsortium:
              Organizations:
                  - *Org1
                  - *Org2
                  - *Org3
                  - *Org4
                  - *Org5
                  - *Org6

  InPaymentChannel:
    Consortium: CrossPaymentConsortium
    Application:
        <<: *ApplicationDefaults
        Organizations:
            - *Org6
            - *Org5
            - *Org4

  CrossPaymentChannel:
    Consortium: CrossPaymentConsortium
    Application:
        <<: *ApplicationDefaults
        Organizations:
            - *Org1
            - *Org2
            - *Org3
            - *Org4